"""add column last_login

Revision ID: 1ca925ff6e2a
Revises: c99a2753ad82
Create Date: 2025-06-25 11:50:50.824443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ca925ff6e2a'
down_revision = 'c99a2753ad82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.Date(), nullable=True))
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', mysql.VARCHAR(length=16), nullable=False))
        batch_op.drop_column('last_login')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
