"""Initialize Project

Revision ID: c99a2753ad82
Revises: 
Create Date: 2025-06-25 11:00:00.367611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99a2753ad82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_user',
    sa.Column('userId', sa.String(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_user')
    # ### end Alembic commands ###
