DEFAULT: &default
  DEBUG: false
  LOG_LEVEL: 'INFO'
  SECRET_KEY: 'I1FG1mL4TDW092'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://salary:salary@202.203.83.219:3306/salary'
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  CAS_SERVER: 'https://cas.yxnu.edu.cn'

  SQLALCHEMY_ECHO: true
  SQLALCHEMY_ENGINE_OPTIONS:
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
  SQLALCHEMY_BINDS:
    local_db : 
      url: "mysql+pymysql://salary:salary@202.203.83.219:3306/salary"
      pool_pre_ping: true
      isolation_level: "READ COMMITTED"
    salary_db : 
      url: "oracle+oracledb://LY_DW:LY%24_DW@202.203.83.225:1521/orcl"
      max_identifier_length: 128

DEVELOPMENT:
  <<: *default
  PORT: 80
  HOST: '0.0.0.0'
  DEBUG: true
  # DATABASE_USERNAME: 'ssgll'
  # DATABASE_PASSWORD: 'guojian'